### ISSUE TITLE
`1 - 1 = -2`

### ISSUE THREAD

**Issue by eriksw** [arkie/dicebot#51] opened 2019-06-27 17:47 UTC
This input `/roll -1d-1` results in:

    [user] rolled *1* - *1* = *-2*

Yes, it's a nonsense input, but it's a bit silly that the output can be a mathematically invalid expression.

**Comment by JShillin** [comment] 2019-07-18 15:52
Looks like you have written -(1d)-1 so its actually -1 - 1 = -2

**Comment by arkie** [comment] 2019-07-25 20:26
As explained by @JShillin, closing out as working as intended 👍

**Closed by arkie** 2019-07-25 20:26 UTC
